### ISSUE TITLE
Create Board Task On Team

### ISSUE THREAD

**Issue by permlap-phola** [tatuga-camp/server-tatuga-school#23]
**Board**
Schema

-src
--board-task
---barod
---colum
---task

```
model Board {
 id       String   @id @default(auto()) @map("_id") @db.ObjectId
 createAt DateTime @default(now())
 updateAt DateTime @updatedAt

title String
description String  
isCompleted Boolen @default(false)


teamId String @db.objectId
team Team @relation([field: teamId, referance:id ])

schoolId String @db.objectId
school School @relation([field: schoolId, referance:id ])

colums Colum[]

}

model Colum {
 id       String   @id @default(auto()) @map("_id") @db.ObjectId
 createAt DateTime @default(now())
 updateAt DateTime @updatedAt

title String
description String?
color String


teamId String @db.objectId
team Team @relation([field: teamId, referance:id ])
schoolId String @db.objectId
school School @relation([field: schoolId, referance:id ])
boardId  String @db.objectId
board Board @relation([field: boardId  , referance:id ])

tasks Task[]
}

model Task{
 id       String   @id @default(auto()) @map("_id") @db.ObjectId
 createAt DateTime @default(now())
 updateAt DateTime @updatedAt

title String
description String?
deadline Date?
isCompleted Boolen @Default(false)


assigneeId String? @db.objectId
assignee MemberOnTeam? @relation([field: assigneeId , referance:id ])

teamId String @db.objectId
team Team @relation([field: teamId, referance:id ])

schoolId String @db.objectId
school School @relation([field: schoolId, referance:id ])

boardId  String @db.objectId
board Board @relation([field: boardId  , referance:id ])

columId String @db.objectId
colum Colum @relation([field: columId , referance:id ])

}
```

- [ ] get a board by ID
_only memeber in team and school admin can access_
```
type Response = Board & {colums: (Colum & {task:Task[]})[]}
```

- [ ] get all board by pagination
_only memeber in team and school admin can access_
```
T = Board
type Pagination<T> = {
  data: T[];
  meta: {
    total: number;
    lastPage: number;
    currentPage: number;
    prev: number | null;
    next: number | null;
  };
}
```
- [ ] create a board
_only memeber in team and school admin can access_

- [ ] update board
_only memeber in team and school admin can access_

- [ ] reorder
_only memeber in team and school admin can access_

- [ ] delete board
_only memeber in team and school admin can access_

**Colum**

- [ ] get colum by ID
_only memeber in team and school admin can access_
```
type Response = Colum & {tasks:Task[]}
```

- [ ] get all colum by boardID
_only memeber in team and school admin can access_
```
type Response = Colum[]
```

- [ ] create
_only memeber in team and school admin can access_

- [ ] update
_only memeber in team and school admin can access_

- [ ] reorder
_only memeber in team and school admin can access_

- [ ] delete
_only memeber in team and school admin can access_

**Task**

- [ ] get a task by ID
_only memeber in team and school admin can access_

- [ ] get all task by columID
_only memeber in team and school admin can access_
```
type Response = Task[]
```

- [ ] create
_only memeber in team and school admin can access_

- [ ] update
_only memeber in team and school admin can access_

- [ ] reorder
_only memeber in team and school admin can access_

- [ ] delete
_only memeber in team and school admin can access_
